source 'http://rubygems.org'

gem 'awesome_print'
gem 'awesome_print'
gem 'heatmap'
gem 'heatmap'
gem 'histogram'
gem 'histogram'
gem 'httparty'
gem 'nokogiri'
gem 'rake'
gem 'soundcloud'
gem 'wordcloud', '~> 0.0.11'
gem 'wordnet'
gem 'wordnet-defaultdb'
gem 'words_counted'
